### ISSUE TITLE
snowflake encoding is not the right one

### ISSUE THREAD

**Issue by maraino** [emojisum/emojisum#37]
According to https://www.unicode.org/emoji/charts/emoji-list.html#2744 snowflake is U+2744, while the emojimap.json shows an extra mapping:

https://github.com/emojisum/emojisum/blob/cb9db27ebae2fa7bcebc24cd0ba627a365d0dbf1/emoji/emojimap.json#L208

This causes `emoji.FromHexString("CB")` to display a blank character.

**Comment by maraino** [comment]
Adding the variation like \u2744\ufe0f (U+2744U+fe0f) displays the nice snowflake (❄️) instead of the small one (❅).

**Comment by maraino** [comment]
Other characters like ✈️ also have a similar issue, and the "cute" variation is required to print the nice version `u2708\ufe0f` instead of `u2708`.

The library that main.go is using seems to have the right variations in the codemap https://github.com/kyokomi/emoji/blob/master/emoji_codemap.go

**Comment by maraino** [comment]
@vbatts I've created a gist with the proper codes to get "cute" emojis.
https://gist.github.com/maraino/5a15ced81d5467cd408ee07adbe88eb4

**Comment by vbatts** [comment]
ah you're right. Let's see.

**Comment by vbatts** [comment]
for ❄️: 
This was just wrong in the first place. `U+FE0F` was just a meant to be a modifier to `U+2744`, not a standalone emoji. 😬 
So it should've been `U+2744` and `U+2744U+FE0F` to begin with.

For ✈️:
We should add the cute one as primary.
